services:
  localtunnel:
    image: boro/localtunnel-client:latest
    container_name: localtunnel_dockerlamp
    restart: "no"
    # CLAVE: Permite acceder al puerto 80 del host (donde Traefik está escuchando)
    network_mode: host 
    # El comando para iniciar el túnel con tu subdominio
    command: lt --port 80 --subdomain dockerlamp-dev # Usaremos un subdominio LT
    labels:
      - "traefik.enable=false" # Ignorar este contenedor en Traefik
