http:
  routers:
    #docker4-local:
    #  entryPoints:
    #    - web 
    #  rule: "Host(`dockerlamp-dev-2.alfonsoalvar.com`)"
    #  middlewares:
        #- redirect-to-https@file
    #    - "strip-root-prefix@file"
    #  service: "apache-service@file"

    docker4-local-ssl:
      entryPoints:
        - websecure 
      rule: "Host(`dockerlamp-dev-2.alfonsoalvar.com`)"
      service: "apache-service@file"
      middlewares:
        - "strip-root-prefix@file"
      tls:
        certResolver: stagingacme
