http:
  services:
    # Definimos un servicio llamado 'apache-service'
    apache-service:
      loadBalancer:
        servers:
          # Apunta directamente al nombre del contenedor/servicio Docker 'apache' en el puerto 80
          # Nota: Usamos el nombre del servicio de Docker Compose como direcci√≥n.
          - url: "http://apache:80"