# traefik/dynamic_conf/docker3.local.yml

http:
  routers:
    # 1. ROUTER HTTP (web): Redirige a HTTPS
    docker4-local:
      entryPoints:
        - web 
      rule: "Host(`dockerlamp-dev-2.alfonsoalvar.com`)"
      middlewares:
        #- redirect-to-https@file # Redirecciona a HTTPS (443)
        - "strip-root-prefix@file"
      #service: "noop@internal" 
      service: "apache-service@file"

    # 2. ROUTER HTTPS (websecure): Sirve la p√°gina
    docker4-local-ssl:
      entryPoints:
        - websecure 
      rule: "Host(`dockerlamp-dev-2.alfonsoalvar.com`)"
      service: "apache-service@file"
      middlewares:
        - "strip-root-prefix@file"
      tls:
        certResolver: stagingacme
